"""Initial tables fixed

Revision ID: 27e9be44676d
Revises: 
Create Date: 2026-03-14 15:54:25.953824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e9be44676d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment="машинный код, например 'first_quest_completed'"),
    sa.Column('title', sa.String(length=200), nullable=False, comment='название для отображения'),
    sa.Column('description', sa.Text(), nullable=True, comment='описание для UI'),
    sa.Column('icon_url', sa.Text(), nullable=True, comment='ссылка на иконку или эмодзи'),
    sa.Column('xp_bonus', sa.Integer(), server_default='0', nullable=False, comment='разовый бонус ОП при разблокировке'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="тип доменного события, например 'quest.completed', 'user.leveled_up'"),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False, comment="тип агрегата-источника, например 'user', 'task'"),
    sa.Column('aggregate_id', sa.UUID(), nullable=False, comment='ID агрегата, породившего событие'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='тело события (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='когда событие было записано'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='когда событие было опубликовано (NULL = ожидает обработки)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_processed_at'), 'outbox_events', ['processed_at'], unique=False)
    op.create_index('ix_outbox_unprocessed', 'outbox_events', ['processed_at', 'created_at'], unique=False, postgresql_where='processed_at IS NULL')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='уникальный идентификатор пользователя (UUID v4)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='уникальный логин'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='электронная почта'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='хеш пароля (bcrypt / argon2)'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='отображаемое имя персонажа'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment='ссылка на аватар'),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False, comment='текущий уровень игрока'),
    sa.Column('experience_points', sa.Integer(), server_default='0', nullable=False, comment='общее количество очков опыта'),
    sa.Column('coins', sa.Integer(), server_default='0', nullable=False, comment='баланс внутриигровой валюты'),
    sa.Column('rank_title', sa.String(length=100), server_default='Новичок', nullable=False, comment='текущее звание / титул'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('crystals', sa.Integer(), server_default='0', nullable=False, comment='премиум-валюта (кристаллы)'),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False, comment='текущая серия дней без пропусков'),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False, comment='максимальная серия дней'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True, comment='время последней активности пользователя'),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False, comment='флаг завершения онбординга'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата создания записи (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата последнего обновления (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='уникальный идентификатор квеста (UUID v4)'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='FK → users.id'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='FK → tasks.id (подзадачи)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='название квеста'),
    sa.Column('description', sa.Text(), nullable=True, comment='расширенное описание (поддерживается markdown)'),
    sa.Column('status', sa.Enum('active', 'completed', 'trial', 'redeemed', 'archived', name='task_status', create_constraint=True), server_default='active', nullable=False, comment='текущий статус квеста'),
    sa.Column('priority', sa.Enum('common', 'uncommon', 'rare', 'epic', name='task_priority', create_constraint=True), server_default='common', nullable=False, comment='редкость / приоритет'),
    sa.Column('category', sa.Enum('work', 'health', 'study', 'creativity', 'family', 'other', name='task_category', create_constraint=True), server_default='other', nullable=False, comment='категория — сфера жизни'),
    sa.Column('recurrence', sa.Enum('none', 'daily', 'weekly', 'monthly', name='task_recurrence', create_constraint=True), server_default='none', nullable=False, comment='паттерн повторения'),
    sa.Column('xp_reward', sa.Integer(), server_default='10', nullable=False, comment='ОП за выполнение'),
    sa.Column('coin_reward', sa.Integer(), server_default='1', nullable=False, comment='монеты за выполнение'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='дедлайн квеста'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='когда квест был выполнен'),
    sa.Column('trial_since', sa.DateTime(timezone=True), nullable=True, comment='дата перехода в статус испытания'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата создания записи (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата последнего обновления (UTC)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_trial_since'), 'tasks', ['trial_since'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='когда пользователь разблокировал достижение'),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_buffs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('buff_type', sa.String(length=50), nullable=False, comment="тип баффа (например, 'xp_boost')"),
    sa.Column('multiplier', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False, comment='множитель баффа'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='дата и время истечения баффа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_buffs_buff_type'), 'user_buffs', ['buff_type'], unique=False)
    op.create_index(op.f('ix_user_buffs_expires_at'), 'user_buffs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_buffs_user_id'), 'user_buffs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_buffs_user_id'), table_name='user_buffs')
    op.drop_index(op.f('ix_user_buffs_expires_at'), table_name='user_buffs')
    op.drop_index(op.f('ix_user_buffs_buff_type'), table_name='user_buffs')
    op.drop_table('user_buffs')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_tasks_trial_since'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_outbox_unprocessed', table_name='outbox_events', postgresql_where='processed_at IS NULL')
    op.drop_index(op.f('ix_outbox_events_processed_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
