"""Add user_buffs table

Revision ID: f578fb3265d8
Revises: a185af92727d
Create Date: 2026-04-27 16:39:16.395047
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f578fb3265d8'
down_revision: Union[str, None] = 'a185af92727d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('buff_type', sa.String(length=50), nullable=False, comment="тип баффа (например, 'xp_boost')"),
    sa.Column('multiplier', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False, comment='множитель баффа'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='дата и время истечения баффа'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_buffs_buff_type'), 'user_buffs', ['buff_type'], unique=False)
    op.create_index(op.f('ix_user_buffs_expires_at'), 'user_buffs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_buffs_id'), 'user_buffs', ['id'], unique=False)
    op.create_index(op.f('ix_user_buffs_user_id'), 'user_buffs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('rank_title', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('weekly_xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_xp')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'rank_title')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.drop_index(op.f('ix_user_buffs_user_id'), table_name='user_buffs')
    op.drop_index(op.f('ix_user_buffs_id'), table_name='user_buffs')
    op.drop_index(op.f('ix_user_buffs_expires_at'), table_name='user_buffs')
    op.drop_index(op.f('ix_user_buffs_buff_type'), table_name='user_buffs')
    op.drop_table('user_buffs')
    # ### end Alembic commands ###
